version: '3'
services:
  walkoff:
    ports:
    - "8080:8080"
    image: "walkoffcyber/walkoff:combinedv1"
    environment:
    - "CACHE={\"type\": \"redis\", \"host\": \"walkoff-redis\", \"port\": 6379}"
    - "HOST=0.0.0.0"
    - "PORT=8080"
    - "ZMQ_RESULTS_ADDRESS=tcp://0.0.0.0:5556"
    - "ZMQ_COMMUNICATION_ADDRESS=tcp://0.0.0.0:5557"
    - "WALKOFF_DB_TYPE=postgresql"
    - "EXECUTION_DB_TYPE=postgresql"
    - "DB_PATH=walkoff"
    - "EXECUTION_DB_PATH=execution"
    - "WALKOFF_DB_HOST=walkoff-postgres"
    - "EXECUTION_DB_HOST=walkoff-postgres"
    - "EXECUTION_DB_USERNAME=walkoff"
    - "EXECUTION_DB_PASSWORD=walkoff"
    - "WALKOFF_DB_USERNAME=walkoff"
    - "WALKOFF_DB_PASSWORD=walkoff"
    depends_on:
    - "walkoff-redis"
    - "walkoff-postgres"
    entrypoint:
    - "sleep"
    - "36000"
  walkoff-redis:
    image: "redis"
  walkoff-postgres:
    image: "postgres"
    environment:
    - "POSTGRES_USER=walkoff"
    - "POSTGRES_PASSWORD=walkoff"