/api/playbooks:
  get:
    tags:
      - Playbooks
    summary: Read all playbooks
    description: ''
    operationId: server.endpoints.playbooks.get_playbooks
    produces:
      - application/json
    parameters:
      - in: query
        name: full
        type: boolean
        required: false
    responses:
      200:
        description: Success
        schema:
          type: array
          items:
            $ref: '#/definitions/AllPlaybooksOverview'
  put:
    tags:
      - Playbooks
    summary: Create a playbook
    description: ''
    operationId: server.endpoints.playbooks.create_playbook
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - in: body
        name: body
        description: The playbook object to be created
        required: true
        schema:
          $ref: '#/definitions/Playbook'
    responses:
      201:
        description: Object created
        schema:
          type: object
          description: All workflows and their associated playbooks. Form of '{playbook_name -> [workflow_name]}'
      211:
        description: Playbook created with empty template
        schema:
          type: object
          description: All workflows and their associated playbooks. Form of '{playbook_name -> [workflow_name]}'
      462:
        description: Playbook already exists.
        schema:
          $ref: '#/definitions/Error'
  post:
    tags:
      - Playbooks
    summary: Update a playbook
    description: ''
    operationId: server.endpoints.playbooks.update_playbook
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - in: body
        name: body
        description: Fields of the playbook object to be updated
        required: true
        schema:
          $ref: '#/definitions/UpdatePlaybook'
    responses:
      200:
        description: Success
        schema:
          type: object
          description: All workflows for the associated playbook. Form of '{playbook_name -> [workflow_name]}'
      461:
        description: Playbook does not exist.
        schema:
          $ref: '#/definitions/Error'
      462:
        description: Playbook with that name already exists.
        schema:
          $ref: '#/definitions/Error'
      463:
        description: Invalid input error.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}:
  parameters:
    - name: playbook_name
      in: path
      description: The name that needs to be fetched.
      required: true
      type: string
  get:
    tags:
      - Playbooks
    summary: Read a playbook
    description: ''
    operationId: server.endpoints.playbooks.read_playbook
    produces:
      - application/json
    responses:
      200:
        description: Success
        schema:
          type: object
          description: All workflows for the specified playbook. Form of '{playbook_name -> [workflow_name]}'
      461:
        description: Object does not exist.
        schema:
          $ref: '#/definitions/Error'
      463:
        description: Invalid input error.
        schema:
          $ref: '#/definitions/Error'
  delete:
    tags:
      - Playbooks
    summary: Delete a playbook
    description: ''
    operationId: server.endpoints.playbooks.delete_playbook
    produces:
      - application/json
    responses:
      200:
        description: Success
      461:
        description: Playbook does not exist.
        schema:
          $ref: '#/definitions/Error'
      515:
        description: I/O error.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/copy:
  post:
    tags:
      - Playbooks
    summary: Copy a playbook
    description: ''
    operationId: server.endpoints.playbooks.copy_playbook
    parameters:
      - name: playbook_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - in: body
        name: body
        description: New playbook name (defaults to <Current_Name>_Copy)
        required: false
        schema:
          type: object
          properties:
            playbook:
              type: string
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      201:
        description: Playbook created
        schema:
          type: object
          description: All workflows and their associated playbooks. Form of '{playbook_name -> [workflow_name]}'
      461:
        description: Playbook does not exist.
        schema:
          $ref: '#/definitions/Error'
      462:
        description: Invalid playbook name. Playbook already exists.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/workflows:
  parameters:
    - name: playbook_name
      in: path
      description: 'The name that needs to be fetched. '
      required: true
      type: string
  get:
    tags:
      - Playbooks
    summary: Read all workflows in playbook
    description: ''
    operationId: server.endpoints.playbooks.get_workflows
    produces:
      - application/json
    responses:
      200:
        description: Success
        schema:
          type: array
          description: The JSON representation of all the workflows for the playbook
          items:
            type: object
            properties:
              schema:
                $ref: '#/definitions/Workflow'
      461:
        description: Playbook does not exist.
        schema:
          $ref: '#/definitions/Error'
      463:
        description: Invalid input error.
        schema:
          $ref: '#/definitions/Error'
  put:
    tags:
      - Workflows
    summary: Create a workflow
    description: ''
    operationId: server.endpoints.playbooks.create_workflow
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - in: body
        name: body
        description: The workflow object to be created
        required: true
        schema:
          $ref: '#/definitions/AddWorkflow'
    responses:
      201:
        description: Workflow created.
        schema:
          $ref: '#/definitions/Workflow'
      211:
        description: Workflow created using default template.
        schema:
          $ref: '#/definitions/Workflow'
      461:
        description: Playbook does not exist.
        schema:
          $ref: '#/definitions/Error'
      462:
        description: Workflow already exists.
        schema:
          $ref: '#/definitions/Error'
  post:
    tags:
      - Workflows
    summary: Update a workflow
    description: ''
    operationId: server.endpoints.playbooks.update_workflow
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - in: body
        name: body
        description: The fields of the workflow object to be updated
        required: true
        schema:
          $ref: '#/definitions/WorkflowUpdate'
    responses:
      200:
        description: Success
        schema:
          type: object
          required: [workflow]
          properties:
            workflow:
              $ref: '#/definitions/Workflow'
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
      462:
        description: Workflow already exists.
        schema:
          $ref: '#/definitions/Error'
      463:
        description: Invalid input error.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/workflows/{workflow_name}:
  parameters:
  - name: playbook_name
    in: path
    description: The name that needs to be fetched.
    required: true
    type: string
  - name: workflow_name
    in: path
    description: 'The name that needs to be fetched. '
    required: true
    type: string
  get:
    tags:
      - Workflows
    summary: Read a workflow
    description: ''
    operationId: server.endpoints.playbooks.read_workflow
    produces:
      - application/json
    responses:
      200:
        description: Success
        schema:
          $ref: '#/definitions/Workflow'
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
      463:
        description: Element not found, or malformed JSON.
        schema:
          $ref: '#/definitions/Error'
  delete:
    tags:
      - Workflows
    summary: Delete a workflow
    description: ''
    operationId: server.endpoints.playbooks.delete_workflow
    produces:
      - application/json
    responses:
      200:
        description: Success
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/workflows/{workflow_name}/risk:
  get:
    tags:
      - Workflows
    summary: Read a workflow's risk value
    description: ''
    operationId: server.endpoints.playbooks.read_workflow_risk
    parameters:
      - name: playbook_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - name: workflow_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
    produces:
      - application/json
    responses:
      200:
        description: Success
        schema:
          type: object
          required: [risk_percent, risk_number]
          properties:
            risk_percent:
              description: Percentage of total risk accumulated
              type: number
              example: 25.63
            risk_number:
              description: Raw number of the risk accumulated by the workflow
              type: number
              example: 153.5
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/workflows/{workflow_name}/copy:
  post:
    tags:
      - Workflows
    summary: Copy a workflow
    description: ''
    operationId: server.endpoints.playbooks.copy_workflow
    parameters:
      - name: playbook_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - name: workflow_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - in: body
        name: body
        description: The new playbook and/or workflow name
        required: false
        schema:
          $ref: '#/definitions/CopyWorkflow'
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      201:
        description: Workflow copied.
        schema:
          $ref: '#/definitions/Workflow'
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
      462:
        description: Workflow already exists.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/workflows/{workflow_name}/execute:
  post:
    tags:
      - Workflows
    summary: Execute a workflow
    description: ''
    operationId: server.endpoints.playbooks.execute_workflow
    parameters:
      - name: playbook_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - name: workflow_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
    produces:
      - application/json
    responses:
      202:
        description: Success asynchronous.
        schema:
          $ref: '#/definitions/WorkflowId'
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/workflows/{workflow_name}/pause:
  post:
    tags:
      - Workflows
    summary: Pause a workflow
    description: ''
    operationId: server.endpoints.playbooks.pause_workflow
    parameters:
      - name: playbook_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - name: workflow_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - name: id
        in: body
        required: true
        schema:
          $ref: '#/definitions/WorkflowId'
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      200:
        description: Success
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/workflows/{workflow_name}/resume:
  post:
    tags:
      - Workflows
    summary: Resume a workflow
    description: ''
    operationId: server.endpoints.playbooks.resume_workflow
    parameters:
      - name: playbook_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - name: workflow_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - name: id
        in: body
        required: true
        schema:
          $ref: '#/definitions/WorkflowId'
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      200:
        description: Success
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
      463:
        description: Invalid UUID.
        schema:
          $ref: '#/definitions/Error'
/api/playbooks/{playbook_name}/workflows/{workflow_name}/save:
  post:
    tags:
      - Workflows
    summary: Save a workflow
    description: ''
    operationId: server.endpoints.playbooks.save_workflow
    parameters:
      - name: playbook_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - name: workflow_name
        in: path
        description: 'The name that needs to be fetched. '
        required: true
        type: string
      - in: body
        name: body
        description: Start action and Actions
        required: true
        schema:
          type: object
          required: [actions]
          properties:
            start:
              type: string
            actions:
              type: array
              items:
                $ref: "#/definitions/Action"
            branches:
              type: array
              items:
                $ref: "#/definitions/Branch"
    produces:
      - application/json
    consumes:
      - application/json
    responses:
      200:
        description: Success
      461:
        description: Playbook or workflow does not exist.
        schema:
          $ref: '#/definitions/Error'
      463:
        description: Invalid action or app in workflow
        schema:
          $ref: '#/definitions/Error'
      515:
        description: I/O error.
        schema:
          $ref: '#/definitions/Error'