version: '3.4'
services:
  builtin:
    build:
      context: .
      dockerfile: Dockerfile
#    image: walkoff_registry:5000/walkoff_app_HelloWorld-v1-0
    env_file:
      - env.txt
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: none
    restart: "no"
    secrets:
      - secret1
secrets:
  secret1:
    file: ./secret_data
    labels:
      foo: bar