matrix:
  include:
    - language: python
      os: linux
      name: "Python 2.7 Unit Tests"
      python: "2.7"
      services:
        - redis-server
      before_install:
        - wget http://www.apache.org/dist/kafka/1.1.0/kafka_2.12-1.1.0.tgz -O kafka.tgz
        - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
        - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
        - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
        - sleep 5
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.5"
      name: "Python 3.5 Unit Tests"
      services:
        - redis-server
      before_install:
      - wget http://www.apache.org/dist/kafka/1.1.0/kafka_2.12-1.1.0.tgz -O kafka.tgz
      - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
      - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
      - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
      - sleep 5
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.6"
      name: "Python 3.6 Unit Tests"
      services:
        - redis-server
      before_install:
      - wget http://www.apache.org/dist/kafka/1.1.0/kafka_2.12-1.1.0.tgz -O kafka.tgz
      - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
      - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
      - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
      - sleep 5
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "2.7"
      name: "Python 2.7 Runtime Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install -r runtimes/python/requirements.txt
        - pip install -r runtimes/python/requirements-test.txt
      script:
        - python -m pytest runtimes/python --rootdir=. -s -v
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.4"
      name: "Python 3.4 Runtime Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install -r runtimes/python/requirements.txt
        - pip install -r runtimes/python/requirements-test.txt
      script:
        - python -m pytest runtimes/python --rootdir=. -s -v
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.5"
      name: "Python 3.5 Runtime Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install -r runtimes/python/requirements.txt
        - pip install -r runtimes/python/requirements-test.txt
      script:
        - python -m pytest runtimes/python --rootdir=. -s -v
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.6"
      name: "Python 3.6 Runtime Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install -r runtimes/python/requirements.txt
        - pip install -r runtimes/python/requirements-test.txt
      script:
        - python -m pytest runtimes/python --rootdir=. -s -v
      branches:
        only:
          - master
          - development

    - language: node_js
      node_js:
        - "node"
      addons:
      name: "UI Unit Tests"
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
          - google-chrome-beta
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - cd walkoff/client
        - npm install
      script: npm run test -- --single-run
      branches:
        only:
          - master
          - development

