matrix:
  include:

  ########################
  ####   Unit Tests   ####
  ########################

    - language: python
      os: linux
      name: "Python 2.7 Unit Tests"
      python: "2.7"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.5"
      name: "Python 3.5 Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.6"
      name: "Python 3.6 Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development

  ##################################
  ####   Python Runtime Tests   ####
  ##################################

    - language: python
      os: linux
      python: "2.7"
      name: "Python 2.7 Runtime Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install -r runtimes/python/requirements.txt
        - pip install -r runtimes/python/requirements-test.txt
      script:
        - cp apps/__init__.py runtimes/python/testapp/__init__.py
        - cp apps/messaging.py runtimes/python/testapp/messaging.py
        - cd runtimes/python
        - pytest -s -v
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.4"
      name: "Python 3.4 Runtime Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install -r runtimes/python/requirements.txt
        - pip install -r runtimes/python/requirements-test.txt
      script:
        - cp apps/__init__.py runtimes/python/testapp/__init__.py
        - cp apps/messaging.py runtimes/python/testapp/messaging.py
        - cd runtimes/python
        - pytest -s -v
      branches:
        only:
          - master
          - development

    - language: python
      os: linux
      python: "3.5"
      name: "Python 3.5 Runtime Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install -r runtimes/python/requirements.txt
        - pip install -r runtimes/python/requirements-test.txt
      script:
        - cp apps/__init__.py runtimes/python/testapp/__init__.py
        - cp apps/messaging.py runtimes/python/testapp/messaging.py
        - cd runtimes/python
        - pytest -s -v
      branches:
        only:
          - master
          - development


    - language: python
      os: linux
      python: "3.6"
      name: "Python 3.6 Runtime Unit Tests"
      services:
        - redis-server
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install -r runtimes/python/requirements.txt
        - pip install -r runtimes/python/requirements-test.txt
      script:
        - cp apps/__init__.py runtimes/python/testapp/__init__.py
        - cp apps/messaging.py runtimes/python/testapp/messaging.py
        - cd runtimes/python
        - pytest -s -v
      branches:
        only:
          - master
          - development

    ###########################
    ####   UI Unit Tests   ####
    ###########################

    - language: node_js
      node_js:
        - "node"
      addons:
      name: "UI Unit Tests"
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
          - google-chrome-beta
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - cd walkoff/client
        - npm install
      script: npm run test -- --watch=false
      branches:
        only:
          - master
          - development

