matrix:
  include:
    - language: python
      os: linux
      python: "2.7"
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development
        except:
          - caching

    - language: python
      os: linux
      python: "3.4"
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development
        except:
          - caching

    - language: python
      os: linux
      python: "3.5"
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development
        except:
          - caching

    - language: python
      os: linux
      python: "3.6"
      install:
        - pip install -r requirements.txt && pip install -r requirements-test.txt
        - pip install coverage
      before_script:
        - python scripts/generate_certificates.py
      script:
        - coverage run run_all_tests.py
        - coverage combine
        - coverage report
      branches:
        only:
          - master
          - development
        except:
          - caching

    - language: node_js
      node_js:
        - "node"
      addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
          - google-chrome-beta
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - cd walkoff/client
        - npm install
      script: npm run test -- --single-run
      branches:
        only:
          - master
          - development

