Playbook:
    type: object
    required: [name]
    properties:
      name:
        type: string

AllPlaybooksOverview:
  type: array
  items:
    $ref: '#/definitions/PlaybookOverview'

PlaybookOverview:
  type: object
  description: Stripped-down view of a playbook
  required: [name, workflows]
  properties:
    name:
      type: string
      description: name of the playbook
    workflows:
      description: workflows inside of this playbook
      type: array
      items:
        $ref: '#/definitions/WorkflowDescription'


WorkflowDescription:
  type: object
  required: [name, uid]
  properties:
    name:
      type: string
      description: name of the workflow
    uid:
      type: string
      description: UID of the workflow

UpdatePlaybook:
    type: object
    required: [name]
    properties:
      name:
        type: string
      new_name:
        type: string

Workflow:
  type: object
  required: [name]
  description: A workflow object
  additionalProperties: false
  properties:
    name:
      description: The name of the workflow. Composed of both its enclosing playbook and its own name
      type: string
      example: HelloWorldWorkflow
    steps:
      description: The steps defined in this workflow.
      type: array
      items:
        $ref: "#/definitions/DisplayStep"
    start:
      description: Name of the starting step
      type: string
      default: start
      example: step1
    accumulated_risk:
      description: The risk which has been accumulated as this workflow has been executed
      type: number
      example: 0.43
      readOnly: true

AddWorkflow:
    type: object
    required: [name]
    properties:
      name:
        type: string

WorkflowUpdate:
    type: object
    required: [name]
    properties:
      name:
        type: string
      new_name:
        type: string

CopyWorkflow:
    type: object
    properties:
      playbook:
        type: string
      workflow:
        type: string

WorkflowId:
  type: object
  required: [id]
  properties:
    id:
      type: string
      description: 32-byte hexidecimal string representing the ID of the workflow
      readOnly: true

Step:
  type: object
  required: [name, action, app]
  description: Encapsulation of executing an action in an app
  additionalProperties: false
  properties:
    name:
      description: Name of the step
      type: string
      example: step1
    action:
      description: The action the step will take
      type: string
      example: pause
    app:
      description: The app to which the action belongs
      type: string
      example: CyberAnalytics
    triggers:
      description: String representation of a list of Trigger objects
      type: array
      items:
        $ref: '#/definitions/Flag'
    device:
      description: Name of the device to use
      type: string
      example: server4
    risk:
      description: risk associated with this step failing
      type: number
      default: 0
      example: 20
    input:
      description: The input arguments to the action
      type: array
      items:
        $ref: '#/definitions/Argument'
    output:
      description: The output of the step after it has been executed
      type: string
      example: result_from_step
    widgets:
      description: The widgets to which this app should send its output
      type: array
      items:
        type: object
        required: [app, name]
        properties:
          app:
            description: Name of the app
            type: string
            example: HelloWorld
          widget:
            description: Name of the widget
            type: string
            example: testWidget
    position:
      description:  position of the step onthe workflow editor
      type: object
      required: [x, y]
      properties:
        x:
          description: x position
          type: number
          example: 443.22
        y:
          description: y position
          type: number
          example: -12.036
    next_steps:
      description: The possible next steps
      type: array
      items:
        $ref: '#/definitions/NextStep'

DisplayStep:
  type: object
  description: Encapsulation of executing an action in an app
  properties:
    name:
      description: Name of the step
      type: string
      example: step1
    action:
      description: The action the step will take
      type: string
      example: pause
    app:
      description: The app to which the action belongs
      type: string
      example: CyberAnalytics
    triggers:
      description: String representation of a list of Trigger objects
      type: array
      items:
        $ref: '#/definitions/Flag'
    device:
      description: Name of the device to use
      type: string
      example: server4
    risk:
      description: risk associated with this step failing
      type: number
      default: 0
      example: 20
    inputs:
      description: The input arguments to the action
      type: array
      items:
        $ref: '#/definitions/Argument'
    widgets:
      description: The widgets to which this app should send its output
      type: array
      items:
        type: object
        required: [app, name]
        properties:
          app:
            description: Name of the app
            type: string
            example: HelloWorld
          widget:
            description: Name of the widget
            type: string
            example: testWidget
    position:
      description:  position of the step onthe workflow editor
      type: object
      required: [x, y]
      properties:
        x:
          description: x position
          type: number
          example: 443.22
        y:
          description: y position
          type: number
          example: -12.036

NextStep:
  type: object
  required: [name]
  description: Encapsualtion of a list of possible steps to take and conditionals (flags) required to be met before taking that step
  additionalProperties: false
  properties:
    name:
      description: The name of the next step
      type: string
      example: step2
    status:
      description: The status return code to use
      type: string
      example: Success
    flags:
      description: List of flags to evaluate
      type: array
      items:
        $ref: '#/definitions/Flag'

Flag:
  type: object
  required: [action]
  description: Takes data and checks it against a condition given by its action Optionally filters the data before checking.
  additionalProperties: false
  properties:
    action:
      description: The action encapsulated by this flag
      type: string
      example: regMatch
    args:
      description: The inputs to the flag
      type: array
      items:
        $ref: '#/definitions/Argument'
    filters:
      description: filters for the data before passing it into the flags
      type: array
      items:
        $ref: '#/definitions/Filter'

Filter:
  type: object
  required: [action]
  description: Filters or otherwise transforms the data given to it
  additionalProperties: false
  properties:
    action:
      description: The action encapsulated by this filter
      type: string
      example: count
    args:
      description: The inputs to the filter
      type: array
      items:
        $ref: '#/definitions/Argument'

Argument:
  type: object
  required: [name, value]
  description: Object used for passing an argument into various actions or device
  properties:
    name:
      type: string
      example: regex
    value:
      example: WALK(.*)
