version: '3.4'
services:
  nmap:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/walkoff_app_nmap:1.0.0
    env_file:
      - env.txt
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: none
    restart: "no"
