version: '3.4'
services:
  power_shell:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/walkoff_app_power_shell:1.0.0
    env_file:
      - env.txt
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: none
      placement:
        constraints: [node.role==manager]
    restart: "no"
