/api/configuration:
  get:
    tags:
      - Configuration
    summary: Reads the configuration
    operationId: walkoff.server.endpoints.configuration.read_config_values
    produces:
      - application/json
    responses:
      200:
        description: Success
        schema:
          $ref: '#/definitions/Configuration'
      401:
        description: Unauthorized access
        schema:
          $ref: '#/definitions/Error'
  post:
    tags:
      - Configuration
    summary: Updates the configuration
    operationId: walkoff.server.endpoints.configuration.update_configuration
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - name: configuration
        in: body
        description: The configuration object
        required: true
        schema:
          $ref: '#/definitions/Configuration'
    responses:
      200:
        description: Success
      401:
        description: Unauthorized access
        schema:
          $ref: '#/definitions/Error'
      515:
        description: Could not write configuration to file
        schema:
          $ref: '#/definitions/Error'