/playbooks:
  get:
    tags:
      - Playbooks
    summary: Read all playbooks
    description: ''
    operationId: walkoff.server.endpoints.playbooks.get_playbooks
    parameters:
      - in: query
        name: full
        schema:
          type: boolean
        required: false
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Playbook'
  post:
    tags:
      - Playbooks
    summary: Create a playbook
    description: ''
    operationId: walkoff.server.endpoints.playbooks.create_playbook
    parameters:
      - in: query
        name: source
        description: The ID of the playbook to clone
        schema:
          type: string
          format: uuid
        required: false
    requestBody:
      description: The playbook object to be created, or the file to be imported
      required: false
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatePlaybook'
        multipart/form-data:
          schema:
            type: file
    responses:
      201:
        description: Object created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Playbook'
      400:
        description: Object exists
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
  patch:
    tags:
      - Playbooks
    summary: Update a playbook
    description: ''
    operationId: walkoff.server.endpoints.playbooks.update_playbook
    requestBody:
      description: Fields of the playbook object to be updated
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdatePlaybook'
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Playbook'
      404:
        description: Playbook does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      400:
        description: Playbook already exists.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'

/playbooks/{playbook_id}:
  parameters:
    - name: playbook_id
      in: path
      description: The ID that needs to be fetched.
      required: true
      schema:
        type: string
        format: uuid
    - in: query
      name: mode
      description: Specify mode as export to download the playbook file
      schema:
        type: string
      required: false
  get:
    tags:
      - Playbooks
    summary: Read or download a playbook
    description: ''
    operationId: walkoff.server.endpoints.playbooks.read_playbook
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Playbook'
      404:
        description: Object does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      400:
        description: Invalid input error.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      515:
        description: I/O error.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
  delete:
    tags:
      - Playbooks
    summary: Delete a playbook
    description: ''
    operationId: walkoff.server.endpoints.playbooks.delete_playbook
    responses:
      204:
        description: Success
      404:
        description: Playbook does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      515:
        description: I/O error.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'


/playbooks/{playbook_id}/workflows:
  parameters:
    - name: playbook_id
      in: path
      description: 'The ID that needs to be fetched. '
      required: true
      schema:
        type: string
        format: uuid
  get:
    tags:
      - Playbooks
    summary: Read all workflows in playbook
    description: ''
    operationId: walkoff.server.endpoints.playbooks.get_workflows_for_playbook
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: array
              description: The JSON representation of all the workflows for the playbook
              items:
                $ref: '#/components/schemas/Workflow'
      404:
        description: Playbook does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'

/workflows:
  get:
    tags:
      - Playbooks
    summary: Read all workflows in playbook
    description: ''
    operationId: walkoff.server.endpoints.playbooks.get_workflows
    parameters:
      - in: query
        name: playbook
        description: The ID of the playbook whose workflows to get
        schema:
          type: string
          format: uuid
        required: false
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: array
              description: The JSON representation of all the workflows for the playbook
              items:
                $ref: '#/components/schemas/Workflow'
      404:
        description: Playbook does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
  post:
    tags:
      - Workflows
    summary: Create a workflow
    description: ''
    operationId: walkoff.server.endpoints.playbooks.create_workflow
    parameters:
      - in: query
        name: source
        description: The ID of the workflow to clone
        schema:
          type: string
          format: uuid
        required: false
    requestBody:
      description: The workflow object to be created
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateWorkflow'
    responses:
      201:
        description: Workflow created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workflow'
      404:
        description: Playbook does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      400:
        description: Workflow already exists.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
  put:
    tags:
      - Workflows
    summary: Update a workflow
    description: ''
    operationId: walkoff.server.endpoints.playbooks.update_workflow
    requestBody:
      description: The fields of the workflow object to be updated
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Workflow'
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              type: object
              required: [workflow]
              properties:
                workflow:
                  $ref: '#/components/schemas/Workflow'
      404:
        description: Playbook or workflow does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
      400:
        description: Workflow already exists.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'

/workflows/{workflow_id}:
  parameters:
    - name: workflow_id
      in: path
      description: 'The ID that needs to be fetched. '
      required: true
      schema:
        type: string
        format: uuid
  get:
    tags:
      - Workflows
    summary: Read a workflow
    description: ''
    operationId: walkoff.server.endpoints.playbooks.read_workflow
    responses:
      200:
        description: Success
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workflow'
      404:
        description: Playbook or workflow does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'

  delete:
    tags:
      - Workflows
    summary: Delete a workflow
    description: ''
    operationId: walkoff.server.endpoints.playbooks.delete_workflow
    responses:
      204:
        description: Success
      404:
        description: Playbook or workflow does not exist.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'

/uuid:
  get:
    tags:
      - Workflows
    summary: Get a new UUID
    description: ''
    operationId: walkoff.server.endpoints.playbooks.get_uuid
    responses:
      201:
        description: Success
        content:
          application/json:
            schema:
              type: object
              required: [uuid]
              properties:
                uuid:
                  $ref: '#/components/schemas/Uuid'
