'/configuration/{key}':
  get:
    tags:
      - Configuration
    summary: Get a configuration key
    description: ''
    operationId: server.endpoints.configuration.config_values
    parameters:
      - name: key
        in: path
        description: 'The configuration key '
        required: true
        type: string
    produces:
      - application/json
    responses:
      200:
        description: Success
        schema:
          type: object
          description: '{[key]: <current value>}'
/configuration/set:
  post:
    tags:
      - Configuration
    summary: Edits a configuration value
    description: ''
    operationId: server.endpoints.configuration.set_configuration
    consumes:
      - multipart/form-data
    produces:
      - application/json
    responses:
      200:
        description: Success