version: '3.4'
services:
  worker:
    image: worker
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    environment:
      # Worker options
      - WORKER_TIMEOUT=30
      - API_GATEWAY_URI=http://api_gateway:8080
      - WALKOFF_USERNAME=admin
      - WALKOFF_PASSWORD=admin

      # Umpire options
      - APPS_PATH=./apps
      - APP_REFRESH=60
      - SWARM_NETWORK=walkoff_default
      - APP_PREFIX=walkoff_app
      - STACK_PREFIX=walkoff
      - DOCKER_REGISTRY=127.0.0.1:5000

      # Redis options
      - REDIS_URI=redis://redis:6379

      # Overrides the environment variables for docker-compose and docker commands on the docker machine at 'DOCKER_HOST'
      # See: https://docs.docker.com/compose/reference/envvars/ for more information.
      - DOCKER_HOST=unix:///var/run/docker.sock
      # - DOCKER_HOST=tcp://ip_of_docker_swarm_manager:2376
      # - DOCKER_TLS_VERIFY=1
      # - DOCKER_CERT_PATH=/Path/to/certs/for/remote/docker/daemon

    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: none
    restart: "no"

  walkoff_app_sdk:
    build:
      context: ../app_sdk
      dockerfile: ./Dockerfile
    image: walkoff_app_sdk
    environment:
      # Worker options
      - WORKER_TIMEOUT=30
      - API_GATEWAY_URI=http://api_gateway:8080
      - WALKOFF_USERNAME=admin
      - WALKOFF_PASSWORD=admin

      # Umpire options
      - APPS_PATH=./apps
      - APP_REFRESH=60
      - SWARM_NETWORK=walkoff_default
      - APP_PREFIX=walkoff_app
      - STACK_PREFIX=walkoff
      - DOCKER_REGISTRY=127.0.0.1:5000

      # Redis options
      - REDIS_URI=redis://redis:6379

      # Overrides the environment variables for docker-compose and docker commands on the docker machine at 'DOCKER_HOST'
      # See: https://docs.docker.com/compose/reference/envvars/ for more information.
      - DOCKER_HOST=unix:///var/run/docker.sock
      # - DOCKER_HOST=tcp://ip_of_docker_swarm_manager:2376
      # - DOCKER_TLS_VERIFY=1
      # - DOCKER_CERT_PATH=/Path/to/certs/for/remote/docker/daemon